<Project><PropertyGroup><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><LangVersion>latest</LangVersion><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile><Deterministic>true</Deterministic><Version>2.1.7</Version><Company>RealtimeTranscription</Company><Copyright>2026</Copyright></PropertyGroup></Project>
